#+TITLE: Shift-And字符串匹配算法
#+AUTHOR: Cauchy
#+EMAIL: pqy7172@gmail.com
#+OPTIONS: ^:nil
#+HTML_HEAD: <link rel="stylesheet" href="./org-manual.css" type="text/css">
* 前言
字符串匹配可以說是计算机科学里最为基础的研究领域之一，其应用的领域极其广泛。每次你在Chrome
浏览器里按下Ctrl-F时，在Vim、Emacs等知名编辑器里方便的搜索替换某个变量时，愉快的使用
Everthing搜索时，每次grep，find时甚至基因配对检测时其背后最为核心的技术就是字符串匹配。一
个更加基础的体现是：其应用领域之广泛以致于其研究者往往也无法预料他们的研究成果可以应用到何
处。

针对我们工作中的应用，就是zealot引擎里对于数据包中特定字符串的匹配。

字符串匹配问题可以理解为从给定的符号序列中找出一个具有某种属性的模式，最简单的例子就是从给
定的字符序列中找出一个给定的字符串。本文将介绍这样一种匹配算法—Shift-And，理论上它比KMP算
法快将近两倍。后文我们也将实际来测量它的性能。

本文主要理论来源于《Flexible Pattern Matching in Strings》一书。这是一本短小精悍的理论书籍，
它具有所有学术书籍共有的特点：高度抽象化、理论化、形式化、公式化以及符号化。正是由于这些特
点，再加上工作中的需要促使本文作者完成这篇文档—一个形象的、具体的、易理解的、多示例的、符
合直觉的算法描述与实现。本文作者的愿景是实现书中每个匹配算法以形成一个系列，进而可以更好的
利用开源匹配库以及在必要的时候应用自己所写的匹配算法。

* 预备知识
一个字符串中所有可能出现的字符组成一个字母表，例如ATCTAGAGA字符串的字母表是{A，C，G，T}。
字符串匹配问题就是在一个大的字符串T中搜索某个字符串p的所有出现位置。其中，T称为文本，p称为
模式串。T和p都定义在同一个字母表上。给定字符串x，y和z，称x是xy的一个前缀，x是yx的一个后缀，
x是yxz的一个因子。字符串匹配是一个与应用场景极其相关的问题。应用场景之一指的是模式串长度以
及字母表大小，依据这些场景的不同最高效的算法可能不同。

解决字符串匹配问题的方法从分类上說共有三类。本文所介绍的Shift-And算法属于前缀匹配类。这种
类别的匹配算法在文本T中由前向后搜索，逐个读入文本字符，以匹配模式串p中的最长公共前缀。当这
个公共前缀的长度等于模式串p的长度时，代表匹配成功。

* Shift-And
定义“向前”：从左向右。定义向后：“从右到左”。

本节将要从各个角度来描述Shift-And算法。从具体到抽象，从示例到一般。在读者看来这样的书籍/文
档流程才是符合人类认知习惯的模式。我们完成一篇文档、书籍不是要写的抽象复杂让读者觉得高深看
不懂，而是以深入浅出平白的语言讲给其他人，确保他人有了形象深刻的认知，然后才能进行抽象的形
式化。尽管这样的流程走下来可能比较繁多，但是没有关系，形象使人深刻，这种繁多还是值得的。

当你发现一本书籍/文档写的极其抽象而让你摸不着头脑，你大可以认为这不是你的理解力问题，而是
作者的表达力问题，因为本质上没有你不能理解的东西：-）。

** 形象描述
本节描述以文本：
#+BEGIN_EXAMPLE
T=a n n u a l _ a n n  o  u  n  c  e
  1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
#+END_EXAMPLE
模式串：
#+BEGIN_EXAMPLE
p=a n n o u n c e
  1 2 3 4 5 6 7 8
#+END_EXAMPLE
为例。忽略其中的空格，它只是为了标下标而存在。t1代表a，而t4t5t6代表ual，t11t12t13t14代表
ounc。同理，p3p4p5代表nou。算法在运行过程中不停的读入文本T，用指针i指示当前读入文本T的位置。
i=7时，表示正在读入t7为_字符。

本算法将要维护一个由0和1组成的掩码串D，它的长度与模式串的长度p.length相同。这个掩码串表征
了模式串中以p1开始向前有多少个字符与文本T中以当前读入位置i为起始（包括i）向后有多少个字符是相等的。
比如D=00010000中的1在第五位（向后看），意味着i开始向后有五个字符与模式串的前五个字符
p1p2p3p4p5组成的字符串相等。可以看到，这样的i=12，即此时已读入到文本的第十二个字符。有了这
些形象化的理解终于可以引出书中专业化的描述：
#+BEGIN_EXAMPLE
“Shift-And算法维护一个字符串的集合，集合中的每个字符串即是模式串p的前缀，同时也是已读入文本的后缀”。
#+END_EXAMPLE

什么时候匹配到整个模式串呢？

可以想见D=10000000时代表成功匹配到整个模式串，结合前文的示例这个意义不言而喻。

在算法进行过程中D将变化，如何随着读入文本T而将D正确的变化呢？还是根据上述具体的例子，我们
先来手工进行这个过程。首先考虑D的初始值，再次给出D表征的意义：
#+BEGIN_EXAMPLE
掩码串D表征了模式串中以p1开始向前有多少个字符与文本T中以当前读入位置i为起始（包括i）向后有多少个字符是相等的。
#+END_EXAMPLE
初始时，T与p中没有一个字符是相等的，所以可以說D的初始值D0=00000000。


** 公式描述
** 伪码表示
** C代码实现

* 性能比较
* 后记
